name: 'Create Jira Release'
description: 'Copies milestone information from Github into Jira release'
inputs:
    repo-token:
        required: true
        description: 'The GITHUB_TOKEN secret'
    milestone:
        required: true
        description: 'The milestone to copy data from'
    milestone-prefix:
        required: false
        description: 'Prefix that should be used for releases created in Jira. This should be product name like Textual, Ephemeral etc.'

runs:
    using: 'node20'
    main: 'index.js'