name: Generate file
description: Writes a file with the given content
inputs:
  content:
    required: true
    description: content of file
  filepath:
    required: true
    description: filepath to write to
  cleanup:
    required: false
    description: "Set to true to remove file at workflow end"
  append:
    required: false
    description: "Set to true to append to file if it exists already"
    default: "false"
  touch:
    required: false
    description: |
      Touch file before writing, creates directory path. Default is "true"
    default: "true"
  filemode:
    required: false
    description: "Octal file mode"
    default: "644"
outputs:
  filepath:
    description: Absolute path to the generated file
runs:
  using: "node20"
  main: main.js
  post: main.js
