name: slack/result-switched
description: |
  Sends a slack message based on the result of a step or job. A message will
  only be sent if inputs.result has a corresponding message provided.
inputs:
  result:
    required: true
    description: |
      The step or job status, one of: success, failure, cancelled or skipped.
  webhook:
    required: true
    description: Webhook recieving the selected message
  success-payload:
    description: Slack message to send on success
  failure-payload:
    description: Slack message to send on failure
  cancelled-payload:
    description: Slack message to send on cancelled
  skipped-payload:
    description: Slack message to send on skipped
runs:
  using: composite
  steps:
      - uses: slackapi/slack-github-action@v2.1.1
        if: ${{ inputs.result == 'success' && inputs.success-payload != '' }}
        with:
          webhook: https://hooks.slack.com/services/${{ inputs.webhook }}
          webhook-type: incoming-webhook
          payload: ${{ inputs.success-payload }}
      - uses: slackapi/slack-github-action@v2.1.1
        if: ${{ inputs.result == 'failure' && inputs.failure-payload != '' }}
        with:
          webhook: https://hooks.slack.com/services/${{ inputs.webhook }}
          webhook-type: incoming-webhook
          payload: ${{ inputs.failure-payload }}
      - uses: slackapi/slack-github-action@v2.1.1
        if: ${{ inputs.result == 'cancelled' && inputs.cancelled-payload != '' }}
        with:
          webhook: https://hooks.slack.com/services/${{ inputs.webhook }}
          webhook-type: incoming-webhook
          payload: ${{ inputs.cancelled-payload }}
      - uses: slackapi/slack-github-action@v2.1.1
        if: ${{ inputs.result == 'skipped' && inputs.skipped-payload != '' }}
        with:
          webhook: https://hooks.slack.com/services/${{ inputs.webhook }}
          webhook-type: incoming-webhook
          payload: ${{ inputs.skipped-payload }}

