name: 'Run Docker Vulnerabilities Scan'
description: 'Checks the Docker containers for vulnerabilities in Quay.'

inputs:
  jira_username:
    required: true
    description: "JIRA username for api access."
  jira_token:
    required: true
    description: "JIRA user api token."
  quayToken:
    required: true
    description: "Oath bearer token from Quay."
  quayTag:
    required: true
    description: "Name of the tag in Quay for which to check for vulnerabilities."
  quay_containers:
      required: true
      description: "A comma-separated list of quay container names, which will be checked for vulnerabilities (eg:tonicai/tonic_web_server, tonicai/tonic_worker."

runs:
  using: "node20"
  main: "index.js"