name: Setup local node action
description: Checkouts (via sparse checkout) and setups a local node action
inputs:
  action-path:
    required: true
    description: Path to action
  sparse-paths:
    required: false
    description: Additional sparse path checkout locations
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ${{ inputs.action-path }}
          ${{ inputs.sparse-paths }}
    - uses: actions/setup-node@v4
      with:
        node-version: "20.x"
        cache: "npm"
        cache-dependency-path: |
          ${{ inputs.action-path }}/package-lock.json
    - shell: bash
      working-directory: ${{ inputs.action-path }}
      run: |
        if [ -f 'package.json' ] || [ -f 'package-lock.json' ]; then
          npm ci --no-audit --prefer-offline
        fi
