name: 'Create Jira Release Notes'
description: 'Creates Jira Release Notes'
inputs:
    fix-version:
        required: true
        description: 'Fix version for which to create release notes. For example: v123'
    jira-username:
        required: true
        description: 'JIRA username for api access.'
    jira-token:
        required: true
        description: 'JIRA user api token.'
    webflow-token:
        required: true
        description: 'Webflow auth token.'
    product-name:
        required: true
        description: 'Name of the product to publish release notes for. Should be structural, ephemeral, or textual.'
    fix-version-prefix:
        required: false
        description: 'Prefix that was used to create releases in Jira. This should be product name like Textual, Ephemeral etc.'

runs:
    using: 'node20'
    main: 'index.js'