name: "Upload GitHub Action workflows logs to opensearch"
description: "Downloads the workflow logs and uploads to opensearch"
inputs:
  github_token:
    description: "GitHub PAT"
  github_org:
    description: "The github organization to read the workflows logs from"
  github_repository:
    description: "The github repository to read the workflows logs from"
  github_run_id:
    description: "The workflow specific run id to read the logs from"
  opensearch_user:
    description: "Username for opensearch server"
  opensearch_password:
    description: "Password for opensearch server"
  opensearch_host:
    description: "The opensearch host"
  opensearch_index:
    description: "The opensearch index"

outputs:
  result:
    description: "Result"
runs:
  using: "docker"
  image: "Dockerfile"
